version: '3.9'

services:
   mongodb:
      container_name: mello-mongodb
      image: mongo:latest
      deploy:
         resources:
            limits:
               cpus: 0.25
               memory: 128M
            reservations:
               memory: 64M
      ports:
         - '27017:27017'

   minio:
      container_name: mello-minio
      image: minio/minio:edge
      command: server /data --console-address ":9001"
      deploy:
         resources:
            limits:
               cpus: 0.25
               memory: 128M
            reservations:
               memory: 64M
      ports:
         - '9000:9000'
         - '9001:9001'
      environment:
         - MINIO_ROOT_USER=mello
         - MINIO_ROOT_PASSWORD=12345678

   influxdb:
      container_name: mello-influxdb
      image: influxdb:latest
      deploy:
         resources:
            limits:
               cpus: 0.05
               memory: 64M
            reservations:
               memory: 32M
      ports:
         - '8086:8086'
      environment:
         - INFLUXDB_INIT_USERNAME=mello
         - INFLUXDB_INIT_PASSWORD=mello
         - INFLUXDB_INIT_ORG=mello
         - INFLUXDB_INIT_BUCKET=mello

   chronograf:
      container_name: mello-chronograf
      image: chronograf:latest
      command: chronograf --influxdb-url=http://influxdb:8086
      deploy:
         resources:
            limits:
               cpus: 0.05
               memory: 64M
            reservations:
               memory: 32M
      ports:
         - '8888:8888'
