version: 2.1

orbs:
   node: circleci/node@4.7
   docker: circleci/docker@2.0.0
   codecov: codecov/codecov@3.2.0
   postman: postman/newman@0.0.2
   k6: k6io/test@1.1.1

jobs:
   release:
      executor:
         name: node/default
         tag: 17.0.1
      steps:
         - checkout
         - node/install-packages
         - run: yarn se-release

workflows:
   bleeding:
      jobs:
         - node/test:
              pkg-manager: yarn
              version: '17.0.1'
              post-steps:
                 - codecov/upload
         - release:
              requires:
                 - 'node/test'
      triggers:
         - schedule:
              cron: '30 12 * * 5'
              filters:
                 branches:
                    only:
                       - main
# Envars Reqiurements
# CODECOV_TOKEN, stands for https://codecov.com write token.
