version: 2.1

orbs:
   node: circleci/node@4.7
   docker: circleci/docker@2.0.0
   codecov: codecov/codecov@3.2.0
   postman: postman/newman@0.0.2
   k6: k6io/test@1.1.1
   snyk: snyk/snyk@1.1.2

jobs:
   release:
      executor:
         name: node/default
         tag: 17.0.1
      steps:
         - checkout
         - node/install-packages
         - run: yarn se-release
   buildThroughWebpack:
      executor:
         name: node/default
         tag: 17.0.1
      steps:
         - checkout
         - node/install-packages:
              pkg-manager: yarn
         - run: yarn build:webpack
         - store_artifacts:
            path: ~/project/dist
   buildThroughDocker:
      executor: docker/docker
      steps:
         - setup_remote_docker:
            version: 19.03.13
         - checkout
         # - docker/check
         - docker/build:
            image: mello/api
         # - snyk/scan:
         #    docker-image-name: mello/api

   # buildThroughNCC
   # buildThroughPkg

workflows:
   bleeding:
      jobs:
         - buildThroughWebpack
         - node/test:
              pkg-manager: yarn
              version: '17.0.1'
              post-steps:
                 - codecov/upload
         - buildThroughDocker:
            # Do not crashed builds because it's waste of time
            requires:
               - 'node/test'

      #    - release:
      #         requires:
      #            - 'node/test'
      # triggers:
      #    - schedule:
      #         cron: '30 12 * * 5'
      #         filters:
      #            branches:
      #               only:
      #                  - main

# Envars Reqiurements
# CODECOV_TOKEN, stands for https://codecov.com write token.
# SNYK_TOKEN, stands for https://snyk.io write token.