version: 2.1

orbs:
   node: circleci/node@4.7
   docker: circleci/docker@2.0.0
   codecov: codecov/codecov@3.2.0
   postman: postman/newman@0.0.2
   k6: k6io/test@1.1.1

workflows:
   dev:
      jobs:
         - node/test:
              pkg-manager: yarn
              version: '17.0.1'
