global:
  enabled: true
  datacenter: dc-mello-staging
server:
  replicas: 1
  resources:
    requests:
      memory: '10Mi'
      cpu: '10m'
    limits:
      memory: '256Mi'
      cpu: '100m'
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  storage: 1Gi
connectInject:
  enabled: true
controller:
  enabled: true